### ISSUE TITLE
Vertical line at "composition du jury" and odd/even pages

### ISSUE THREAD

**Issue by quentinmiagoux** [abichat/hadamardown#2]
Hello @abichat,

I know you might not change the template as it should follow the Paris-Saclay template, but just to let you know.
It is a bit picky but there is something wrong in the cover page of Paris-Saclay latex template.
The vertical line at "composition du jury" will come in black with this template while in the PDF/word of  Paris-Saclay template it is prune.
I think they made a mistake in the template.tex at :

`\begin{tabular}{|p{8cm}l}`
`\arrayrulecolor{Prune}`

In my template, I slightly modified the template.tex to have this prune line just by inverting these two lines

`\arrayrulecolor{Prune}`
`\begin{tabular}{|p{8cm}l}`

Also, one more thing, this time related to the thesisdown package. 
Correct me if I'm wrong but I think that the template has reversed odd and even pages, I tried to print a test once and the margin supposed to be in the bookbinding is upside down. Because I modified the basic template, I don't know if it is me that induced this or if it was already there. Anyway, I fixed it, so if you have the same problem I could propose something.

Best,

**Comment by abichat** [comment]
Thanks for fixing the color! You can add yourself to the description file as a contributor (ctb) if you want. 

For the odd and even pages, I'm not sure to understand. For both my thesis and a new one from template, the numbering at the top of a double page is as follow: 
`page ________ # chapter   |   # section ________ page`
which is what is expected.

**Comment by quentinmiagoux** [comment]
I'm sorry, it is not well explained.

It is not related to the numbering of the pages but to the bookbinding margins (which I supposed is based on odd/even pages). 
Here is an example from the  paris saclay a template after knitting, if you view it as a book in the viewer, you see that there is a bigger margin on pages based on bookbinding. It is made for printing, so the bookbinding doesn't after the readability.

The problem here is that the biggest margin side is reversed according to the bookbinding.

![image](https://user-images.githubusercontent.com/33721458/104596626-85727d00-5674-11eb-8dd5-7abfd5479943.png)

**Comment by abichat** [comment]
Yes, I didn't notice that. I would be wonderful if you could fix it :)
